eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true


spring:
  application:
    name: Config-Service

server:
  boot: springboot
  port: 9081