eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true


spring:
  application:
    name: Spring-Boot-Example1
  cloud:
    zookeeper:
      enabled: true
      connect-string: 127.0.0.1:2181
      snail-api:
        enabled: true
        root: /snail/springboot/urls
        temp: false
      config:
        root: /configs
        defaultContext: garlic
        enabled: true
        watcher:
          enabled: true
  profiles:
    active: dev

server:
  port: 8081

logging:
  level:
    root: DEBUG

#testconfig: 123