eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: true
  sever:
  #waitTimeInMsWhenSyncEmpty: 5


spring:
  application:
    name: eureka-server